=== arnab01/Placement-Portal/xml/arnab.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Results (Company)+>
<!ATTLIST Results
  xmlns CDATA #FIXED ''>

<!ELEMENT Company (Companyname,roundname,studentname,rollno,status,role,
                   offertype)>
<!ATTLIST Company
  xmlns CDATA #FIXED ''>

<!ELEMENT Companyname (#PCDATA)>
<!ATTLIST Companyname
  xmlns CDATA #FIXED ''>

<!ELEMENT roundname (#PCDATA)>
<!ATTLIST roundname
  xmlns CDATA #FIXED ''>

<!ELEMENT studentname (#PCDATA)>
<!ATTLIST studentname
  xmlns CDATA #FIXED ''>

<!ELEMENT rollno (#PCDATA)>
<!ATTLIST rollno
  xmlns CDATA #FIXED ''>

<!ELEMENT status (#PCDATA)>
<!ATTLIST status
  xmlns CDATA #FIXED ''>

<!ELEMENT role (#PCDATA)>
<!ATTLIST role
  xmlns CDATA #FIXED ''>

<!ELEMENT offertype (#PCDATA)>
<!ATTLIST offertype
  xmlns CDATA #FIXED ''>

=== arnab01/Placement-Portal/xml/arnab.xml
<?xml version="1.0"?>
<!DOCTYPE schedules SYSTEM "arnab.dtd">
<?xml-stylesheet type="text/xsl" href="arnab.xsl" ?>


<Results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="arnab.xsd">

<Company>
<Companyname> Cisco </Companyname>
<roundname>Aptitude and Coding </roundname>
<studentname> Arnab </studentname>
<rollno> cb.en.u4cse17309</rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Cisco </Companyname>
<roundname>Aptitude and Coding </roundname>
<studentname> Anjali </studentname>
<rollno> cb.en.u4cse17307</rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Cisco </Companyname>
<roundname>Aptitude and Coding </roundname>
<studentname> Aradhana </studentname>
<rollno> cb.en.u4cse17308</rollno>
<status> rejected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Cisco </Companyname>
<roundname>Interview </roundname>
<studentname> Arnab </studentname>
<rollno> cb.en.u4cse17309</rollno>
<status> rejected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Cisco </Companyname>
<roundname>Interview </roundname>
<studentname> Anjali </studentname>
<rollno> cb.en.u4cse17307</rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>


<Company>
<Companyname> Cisco </Companyname>
<roundname>Selected </roundname>
<studentname> Anjali </studentname>
<rollno> cb.en.u4cse17307</rollno>
<status> selected </status>
<role> SR engineer </role>
<offertype> FTE </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>Online Coding </roundname>
<studentname> Parvathi </studentname>
<rollno> cb.en.u4cse17340 </rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>Online Coding </roundname>
<studentname> Arnab </studentname>
<rollno> cb.en.u4cse17309 </rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>Online Coding </roundname>
<studentname> Harsha </studentname>
<rollno> cb.en.u4cse17440 </rollno>
<status> rejected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>Tech interview </roundname>
<studentname> Parvathi </studentname>
<rollno> cb.en.u4cse17340 </rollno>
<status> selected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>=Tech interview </roundname>
<studentname> Arnab </studentname>
<rollno> cb.en.u4cse17309 </rollno>
<status> rejected </status>
<role> None </role>
<offertype> None </offertype>
</Company>

<Company>
<Companyname> Aptean </Companyname>
<roundname>selects</roundname>
<studentname> Parvathi </studentname>
<rollno> cb.en.u4cse17340 </rollno>
<status> selected </status>
<role> SDE </role>
<offertype> FTE </offertype>
</Company>

</Results>
